[build]
  command = "pip install -r requirements.txt && echo 'Build complete'"
  functions = "api"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.10.12"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"
  PIP_QUIET = "1"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
